services:
  db:
    image: postgres:13.10
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - .env

  backend:
    image: rdk7777/kittygram_backend
    volumes:
      - static:/app/static
      - media:/app/media
    env_file:
      - .env

  frontend:
    image: rdk7777/kittygram_frontend
    command: cp -r /app/build/. /static/ && tail -f /dev/null
    volumes:
      - static:/static
    env_file:
      - .env

  gateway:
    image: rdk7777/kittygram_gateway
    volumes:
      - static:/var/www/static
      - media:/var/www/media
    ports:
      - "9000:8000"
    depends_on:
      - backend
      - frontend

volumes:
  pg_data:
  static:
  media:
