server {
    listen 8000;

    # Скрываем версию Nginx из заголовков и страниц ошибок
    server_tokens off;

    # Фронтенд (React build)
    location / {
        root   /var/www/static;
        index  index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # Статика Django (админка, CSS, JS)
    location /static/ {
        alias /var/www/static/;
    }

    # Проксирование API
    location /api/ {
        proxy_pass http://backend:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Проксирование Админки
    location /admin/ {
        proxy_pass http://backend:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Медиафайлы (картинки котов)
    location /media/ {
        alias /var/www/media/;
    }
}
